# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
github_username: gernotstarke
github: metadata

search             : true
search_full_content: true

minimal_mistakes_skin    : "default" 

# Site Settings
locale                   : "de"
title                    : "arc42"
title_separator          : "-"
name                     : "Dr. Gernot Starke"
description              : "Resourcen für Softwarearchitektur."
# url                      : "https://www.arc42.de" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
url                      : "https://www.arc42.de" 
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "arc42/arc42.de-site" # GitHub username/repo-name
teaser                   : /images/arc42-splash-landingpage.jpg 
breadcrumbs            : false # true, false (default)
words_per_minute         : 200


# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :

# Social Sharing
twitter:
  username               : arc42Tipps

social:
  type                   : Organization # Person or Organization (defaults to Person)
  name                   : arc42 # If the user or organization name differs from the site's name

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :


# Site Author
author:
  name             : "Dr. Gernot Starke"
  avatar           : /images/Gernot-avatar-2016.jpg # path of avatar image, e.g. "/images/bio-photo.jpg"
  bio              : "INNOQ fellow, (co)founder of arc42, founder of aim42"
  location         : "Cologne, Germany"
  email            : info@arc42.org
  uri              : https://www.gernotstarke.de
  github           : arc42
  google_plus      :
  stackoverflow    :
  twitter          : arc42Tipps
  xing             : arc42

## make the feed-url go away!!

atom_feed:
  hide             : true

# Reading Files
include:
  - .htaccess
  - _pages
  - robots.txt

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - package.json
  - README.md
  - images/originale
  - Dockerfile
  - _manage-site.sh
  - _docker*
  - zz-site/
  - _site/
  - archive/
  - test/
  - arc42de-site.code-workspace
  - _docker-compose-dev.yml
 

keep_files:
  - .git
  - robots.txt

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# the botpoison browser script is required for spam-protection in the Anmeldung-Form
# see https://documentation.formspark.io/setup/spam-protection.html#botpoison
head_scripts:
  - 

# Outputting
permalink: /:categories/:title/
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jemoji
 
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-include-cache
  - jekyll-sitemap
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: true
      related: true
